In [10]:
import pytesseract
from PIL import Image
import cv2
import numpy as np

import re
import pandas as pd

pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'

In [2]:
def preprocess_img_gray(image_path, ):
    """Preprocess DOSBox screenshot for better OCR"""
    
    img = cv2.imread(image_path)
    #Read image
    
    img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    #Convert to grayscale

    _, thresh = cv2.threshold(img_gray, 100, 255, cv2.THRESH_BINARY)

    denoised = cv2.fastNlMeansDenoising(thresh)
    #Denoise

    return denoised

# Usage
processed_image = preprocess_img_gray(r'eli_image_example1.png')

text = pytesseract.image_to_string(processed_image)
print(text)

Milagres
Ailton
Evanf1son
Estevan
Mar ins
Ricardo
Ronaldo
Tau
Fagundes
Renato
Claudio

Irénio

Reinaldo
Rinaldo

Celso

Viver i
Cléudio Lopez

ATLETICO
5? lugar © pontos
18 JORNADA

AMERICA BRA
a

72 lugar © pontos

30000 lugares 11762_sécios

235000
22700
Preco dos bilhetes

In [3]:
Image.fromarray(processed_image).show()

In [4]:
new_img = processed_image * 200
Image.fromarray(new_img).show()

In [5]:
Image.fromarray(cv2.cvtColor(processed_image, cv2.COLOR_BGR2GRAY)).show()

error: OpenCV(4.13.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.simd_helpers.hpp:92: error: (-15:Bad number of channels) in function '__cdecl cv::impl::`anonymous-namespace'::CvtHelper<struct cv::impl::`anonymous namespace'::Set<3,4,-1>,struct cv::impl::A0xb1d3297b::Set<1,-1,-1>,struct cv::impl::A0xb1d3297b::Set<0,2,5>,4>::CvtHelper(const class cv::_InputArray &,const class cv::_OutputArray &,int)'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 1

In [ ]:
Image.fromarray(cv2.cvtColor(processed_image, cv2.COLOR_BGR2RGB)).show()

In [ ]:
Image.fromarray(cv2.cvtColor(processed_image, cv2.COLOR_BGR2HSV)).show()

In [ ]:
extracted_text

'Ni lagres\nníltos\nPan aa\nEstenan\nMin\nTFicardo\nTera dto\nTan\nFaquindos\nTesato\nClaudio\n\nIrénio\n\nFeinldo\nTinaldo\n\nol\n\nUiueor *\nGClândio Lojes\n\nATLETICO\n5º lugar O pontos\n1º JORNADA\n\nAMERICA tm\nn\n\n7 ugar 6 pontos\n\nS0 la ME cios\n\nET\nFEx\nPresao dos bi Hetes\n\n'

In [ ]:
img = Image.fromarray(cv2.cvtColor(processed_image, cv2.COLOR_BGR2HSV)).show()
extracted_text = pytesseract.image_to_string(cv2.cvtColor(processed_image, cv2.COLOR_BGR2HSV), lang='por')

In [ ]:
salary_auction_frame = extracted_text.split('\n')

In [ ]:
player = salary_auction_frame[2].split(' ')[1]
player_pos = salary_auction_frame[3].split(' ')[1]
player_str = salary_auction_frame[5].split(' ')[1]
player_team = salary_auction_frame[7].split(' ')[2]
player_price = salary_auction_frame[9].split(' ')[2]
player_minimum_wage = salary_auction_frame[11].split(' ')[2]

IndexError: list index out of range

In [ ]:
def extract_salary_auction_info(salary_auction_frame):
    player = salary_auction_frame[2].split(' ')[1]
    player_pos = salary_auction_frame[3].split(' ')[1]
    player_str = salary_auction_frame[5].split(' ')[1]
    player_team = salary_auction_frame[7].split(' ')[2]
    player_price = salary_auction_frame[9].split(' ')[2]
    player_minimum_wage = salary_auction_frame[11].split(' ')[2]
    
    return {
        'name': player,
        'position': player_pos,
        'strength': player_str,
        'team': player_team,
        'price': player_price,
        'minimum_wage': player_minimum_wage
    }

In [ ]:
def extract_salary_auction_info(salary_auction_frame):
    player = salary_auction_frame[2].split(' ')[1]
    player_pos = salary_auction_frame[3].split(' ')[1]
    player_str = salary_auction_frame[5].split(' ')[1]
    player_team = salary_auction_frame[7].split(' ')[2]
    player_price = salary_auction_frame[9].split(' ')[2]
    player_minimum_wage = salary_auction_frame[11].split(' ')[2]
    
    return {
        'name': player,
        'position': player_pos,
        'strength': player_str,
        'team': player_team,
        'price': player_price,
        'minimum_wage': player_minimum_wage
    }

In [ ]:
print(f"Player: {player}, Position: {player_pos}, Strength: {player_str}, Team: {player_team}, Price: {player_price}, Minimum Wage: {player_minimum_wage}")

Player: Viola, Position: , Strength: 29, Team: PALMEIRAS, Price: 87000, Minimum Wage: 2000

In [ ]:
1/0

ZeroDivisionError: division by zero

## Video experiment

In [ ]:
from src.functions import save_video_frames

save_video_frames('Data/Video/Elifoot_vid1.mp4', 'Data/Frames', 1)

ModuleNotFoundError: No module named 'skimage'

## Frame labeller code

In [ ]:
import os

In [ ]:
import os
from PIL import Image

frames_folder = 'Data/Frames'

for frame in os.listdir(frames_folder):
    frame_path = os.path.join(frames_folder, frame)
    img = Image.open(frame_path)
    img.resize((200, 200)).show(title = frame_path)
    class_choice = input('Frame_class')
    if class_choice == 'sk':
        continue
    copy_frame_to_folder(frame_path, class_choice)
    img.close()

In [ ]:
import os
from PIL import Image

frames_folder = 'Data/Screenshots'

for frame in os.listdir(frames_folder):
    frame_path = os.path.join(frames_folder, frame)
    img = Image.open(frame_path)
    img.resize((200, 200)).show(title = frame_path)
    class_choice = input('Frame_class')
    if class_choice == 'sk':
        continue
    copy_frame_to_folder(frame_path, class_choice)
    img.close()

In [7]:
def preprocess_img_gray(image_path, ):
    """Preprocess DOSBox screenshot for better OCR"""
    
    img = cv2.imread(image_path)
    #Read image
    
    img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    #Convert to grayscale

    _, thresh = cv2.threshold(img_gray, 100, 255, cv2.THRESH_BINARY)

    denoised = cv2.fastNlMeansDenoising(thresh)
    #Denoise

    return img, img_gray, denoised

# Usage
processed_image1, processed_image2, processed_image3 = preprocess_img_gray(r'eli_image_example1.png')

text = pytesseract.image_to_string(processed_image1)
print(text)

text = pytesseract.image_to_string(processed_image2)
print(text)

text = pytesseract.image_to_string(processed_image3)
print(text)

ATLETICO casa
5? lugar © pontos
18 JORNADA


Milagres
Aflton
Evanf1son
Estevan
Mar ins
Ricardo
Ronaldo
Tau
Fagundes
Renato
Claudio

Irénio

Reinaldo
Rinaldo

Celso

Wiver Is
Cléudio Lopez

ATLETICO
5? lugar © pontos
18 JORNADA

AMERICA BRA
A

72 lugar © pontos

30000 lugares 11762 _sécios

235000
22700
Preco dos bilhetes


Milagres
Ailton
Evanf1son
Estevan
Mar ins
Ricardo
Ronaldo
Tau
Fagundes
Renato
Claudio

Irénio

Reinaldo
Rinaldo

Celso

Viver i
Cléudio Lopez

ATLETICO
5? lugar © pontos
18 JORNADA

AMERICA BRA
a

72 lugar © pontos

30000 lugares 11762_sécios

235000
22700
Preco dos bilhetes

In [ ]:
Image.fromarray(processed_image2[:, 200:220, :])

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [ ]:
config = '--psm 6'
text = pytesseract.image_to_string(Image.fromarray(processed_image3), config=config)
print(text)

G Milagres 19 1000 0 AMERICA BRA
Ailton 190 800 0 a
D Evanilson 11 900 0 72 lugar © pontos
Estevan 13 1400 0 30000 lugares _11762_sécios
Mar ins 11 900 0
Ricardo 13 1500 0
Ronaldo 3 900 0
M Tau 8 1000 0
Fagundes 12 1400 0
Renato 8 700 0
Claudio 3 900 0
Irénio 11 1000 0
Reinaldo 11 1100 0
@ Rinaldo 12 1400 0
Celso N 3 1000 0
Viver 12 1300 0
Claudio Lopez 21 5500 « 0
ATLETICO cASA Dinheiro: 235000
52 lugar 0 pontos Ordenados: 22700
12 JORNADA Preco dos bilhetes: 10

In [ ]:
[i.split(' ') for i in text.split('\n')]

[['G', 'Milagres', '19', '1000', '0', 'AMERICA', 'BRA'],
 ['Ailton', '190', '800', '0', 'a'],
 ['D', 'Evanilson', '11', '900', '0', '72', 'lugar', '©', 'pontos'],
 ['Estevan', '13', '1400', '0', '30000', 'lugares', '_11762_sécios'],
 ['Mar', 'ins', '11', '900', '0'],
 ['Ricardo', '13', '1500', '0'],
 ['Ronaldo', '3', '900', '0'],
 ['M', 'Tau', '8', '1000', '0'],
 ['Fagundes', '12', '1400', '0'],
 ['Renato', '8', '700', '0'],
 ['Claudio', '3', '900', '0'],
 ['Irénio', '11', '1000', '0'],
 ['Reinaldo', '11', '1100', '0'],
 ['@', 'Rinaldo', '12', '1400', '0'],
 ['Celso', 'N', '3', '1000', '0'],
 ['Viver', '12', '1300', '0'],
 ['Claudio', 'Lopez', '21', '5500', '«', '0'],
 ['ATLETICO', 'cASA', 'Dinheiro:', '235000'],
 ['52', 'lugar', '0', 'pontos', 'Ordenados:', '22700'],
 ['12', 'JORNADA', 'Preco', 'dos', 'bilhetes:', '10'],
 ['']]

In [ ]:
row_numbers

[None,
 None,
 <re.Match object; span=(0, 2), match='19'>,
 <re.Match object; span=(0, 4), match='1000'>,
 <re.Match object; span=(0, 1), match='0'>,
 None,
 None]

In [ ]:
counter

20

In [11]:
config = '--psm 6'
text = pytesseract.image_to_string(Image.fromarray(processed_image2[0:300,:350]), config=config)

d = {}
counter = 0

for row in text.split('\n'):
    if row.strip() == '':
        continue
    row_components = row.split(' ')
    if row_components[0] == 'G':
        pos = row_components.pop(0)
    if row_components[0] == 'D':
        pos = row_components.pop(0)
    elif row_components[0] == 'M':
        pos = row_components.pop(0)
    elif row_components[0] == 'A' or row_components[0] == '@':
        pos = row_components.pop(0)

    row_numbers = [re.match(r'\d+', row) for row in row_components]
    if row_numbers[1] is None:
        name_string = row_components[0] + row_components[1]
    else:
        name_string = row_components[0]
    #Test if name is first tring or frist two based of where Strength is
    numbers_list = [int(potential_number.group()) for potential_number in row_numbers if potential_number]

    d[counter] = [pos] + [name_string] + numbers_list
    counter += 1
    
d

{0: ['G', 'Milagres', 10, 1000, 0],
 1: ['G', 'Ailton', 10, 800, 0],
 2: ['D', 'Evanilson', 11, 900],
 3: ['D', 'Estevan', 13, 1400, 0],
 4: ['D', 'Marins', 11, 900, 0],
 5: ['D', 'Ricardo', 13, 1500, 0],
 6: ['D', 'Ronaldo', 3, 900, 0],
 7: ['M', 'Tau', 8, 1000, 0],
 8: ['M', 'Fagundes', 12, 1400, 0],
 9: ['M', 'RenatoB', 700, 0],
 10: ['M', 'Claudio', 3, 900, 0],
 11: ['M', 'Irénio', 11, 1000, 0],
 12: ['M', 'Reinaldo', 11, 1100, 0],
 13: ['A', 'Rinaldo', 12, 1400, 0],
 14: ['A', 'CelsoN', 9, 1000, 0],
 15: ['A', 'Wiver', 12, 1300],
 16: ['A', 'CléudioLopez', 21, 5500, 0]}

In [12]:
pd.DataFrame.from_dict(d, orient='index', columns=['Position', 'Name', 'Strength', 'Salary', 'Goals'])

   Position          Name  Strength  Salary  Goals
0         G      Milagres        10    1000    0.0
1         G        Ailton        10     800    0.0
2         D     Evanilson        11     900    NaN
3         D       Estevan        13    1400    0.0
4         D        Marins        11     900    0.0
5         D       Ricardo        13    1500    0.0
6         D       Ronaldo         3     900    0.0
7         M           Tau         8    1000    0.0
8         M      Fagundes        12    1400    0.0
9         M       RenatoB       700       0    NaN
10        M       Claudio         3     900    0.0
11        M        Irénio        11    1000    0.0
12        M      Reinaldo        11    1100    0.0
13        A       Rinaldo        12    1400    0.0
14        A        CelsoN         9    1000    0.0
15        A         Wiver        12    1300    NaN
16        A  CléudioLopez        21    5500    0.0

In [ ]:
import re

row_numbers = [re.match(r'\d+', row) for row in row_components]
numbers_list = [int(potential_number.group()) for potential_number in row_numbers if potential_number]

In [ ]:
numbers_list

[19, 1000, 0]

In [ ]:
processed_image3#[:, 200:220]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(400, 640), dtype=uint8)

In [ ]:
config = '--psm 6'
text = pytesseract.image_to_string(Image.fromarray(processed_image3[0:300,200:230]), config=config)
print(text)

—
10
10
11
13
11
13
9
8
12
8
9
11
11
12
9
12
21

In [32]:
' '.join(row_components)

'Cléudio Lopez'

In [ ]:
player_text = pytesseract.image_to_string(Image.fromarray(processed_image3[0:300,0:150]), config=config)

all_pos = []
all_names = []
for row in player_text.split('\n'):
    if row.strip() == '':
        continue
    row_components = row.split(' ')
    if row_components[0] == 'G':
        pos = row_components.pop(0)
    if row_components[0] == 'D':
        pos = row_components.pop(0)
    elif row_components[0] == 'M':
        pos = row_components.pop(0)
    elif row_components[0] == 'A' or row_components[0] == '@':
        pos = row_components.pop(0)
    all_pos += [pos]
    all_names += [' '.join(row_components)]

strength_text = pytesseract.image_to_string(Image.fromarray(processed_image3[0:300,200:230]), config=config)
strength_values = [int(sth_v) for sth_v in strength_text.split('\n') if re.match(r'\d+', sth_v)]

salary_text = pytesseract.image_to_string(Image.fromarray(processed_image3[0:300,230:265]), config=config)
salary_values = [int(sal_v) for sal_v in salary_text.split('\n') if re.match(r'\d+', sal_v)]

#TO DO - Capture "*"/"." for contract length

In [47]:
[int(i) for i in strength_text.split('\n') if re.match(r'\d+', i)]

[10, 10, 11, 13, 11, 13, 9, 8, 12, 8, 9, 11, 11, 12, 9, 12, 21]

In [51]:
pd.DataFrame({'Position': all_pos, 'Name': all_names, 'Strength': strength_values, 'Salary': salary_values})

   Position           Name  Strength  Salary
0         G       Milagres        10    1000
1         G         Ailton        10     800
2         D      Evanflson        11     300
3         D        Estevan        13    1400
4         D        Mar ins        11     300
5         D        Ricardo        13    1500
6         D        Ronaldo         9     300
7         M            Tau         8    1000
8         M       Fagundes        12    1400
9         M         Renato         8     700
10        M        Claudio         9     300
11        M         Irénio        11    1000
12        M       Reinaldo        11    1100
13        A        Rinaldo        12    1400
14        A       Celso Rn         9    1000
15        A          Viver        12    1300
16        A  Cléudio Lopez        21    5500

In [74]:
config = '--psm 7 --oem 3 -c tessedit_char_whitelist=0123456789*.'

salary_text = pytesseract.image_to_string(Image.fromarray(processed_image3[0:300,220:295]), config=config)
print(salary_text)

*

In [75]:
Image.fromarray(processed_image3[0:300,220:295]).show()